#!/usr/bin/env node

/*
 * HAND-WRITTEN FOR THE FIXTURE — this is not a Yarn-generated .pnp.cjs.
 *
 * A real one is generated by `yarn install`, is several thousand lines long, and
 * ends by installing the resolution hook into Node (`setupCompatibilityLayer`,
 * `module._resolveFilename` patching) so that every `require`/`import` in the
 * process goes through the map below instead of walking node_modules.
 *
 * This file carries the *data* and none of the runtime: the package registry,
 * the dependency edges, and the on-disk location of the one unplugged package.
 * That is deliberate, and it is what the fixture is for — the data is what a
 * declarative reader opens (AGENTS.md rule 10: read files, never invoke a
 * package manager), and the missing hook is precisely why `tsc` run as a plain
 * Node process reports `Cannot find module '@acme/http'` on a project that is
 * installed and correct.
 *
 * Consequence worth knowing before writing a reader against it: the shape below
 * is the older, readable `packageRegistryData` form. Yarn ≥ 3.3 emits the same
 * information as a single JSON string assigned to `RAW_RUNTIME_STATE`. A reader
 * that only handles this shape will not handle a real modern lockfile.
 */

const packageRegistryData = [
  [
    null,
    [
      [
        null,
        {
          packageLocation: "./",
          packageDependencies: [["@acme/http", "npm:1.2.0"]],
          linkType: "SOFT",
        },
      ],
    ],
  ],
  [
    "acme-portal",
    [
      [
        "workspace:.",
        {
          packageLocation: "./",
          packageDependencies: [
            ["acme-portal", "workspace:."],
            ["@acme/http", "npm:1.2.0"],
          ],
          linkType: "SOFT",
        },
      ],
    ],
  ],
  [
    "@acme/http",
    [
      [
        "npm:1.2.0",
        {
          packageLocation: "./.yarn/unplugged/@acme-http-npm-1.2.0-a1b2c3d4e5/node_modules/@acme/http/",
          packageDependencies: [
            ["@acme/http", "npm:1.2.0"],
            ["qs", "npm:6.11.2"],
          ],
          linkType: "HARD",
        },
      ],
    ],
  ],
  [
    "qs",
    [
      [
        "npm:6.11.2",
        {
          packageLocation: "./.yarn/cache/qs-npm-6.11.2-placeholder.zip/node_modules/qs/",
          packageDependencies: [["qs", "npm:6.11.2"]],
          linkType: "HARD",
        },
      ],
    ],
  ],
];

module.exports = { packageRegistryData };
